ERROR - 2024-04-27 22:35:05 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\codeigniter4_2024\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\codeigniter4_2024\system\Database\BaseConnection.php(392): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4_2024\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4_2024\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\codeigniter4_2024\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\codeigniter4_2024\system\Test\CIUnitTestCase.php(249): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(2315): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(2238): PHPUnit\Framework\TestCase->invokeHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter), 'testBeforeTestM...', 'testBeforeTestM...')
#7 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(474): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#8 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestRunner.php(98): PHPUnit\Framework\TestCase->runBare()
#9 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(337): PHPUnit\Framework\TestRunner->run(Object(ExampleDatabaseTest))
#10 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#11 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#12 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(62): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\TextUI\Application.php(200): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\xampp\htdocs\codeigniter4_2024\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-04-27 22:35:06 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\codeigniter4_2024\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\codeigniter4_2024\system\Database\BaseConnection.php(392): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4_2024\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4_2024\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\codeigniter4_2024\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\codeigniter4_2024\system\Test\CIUnitTestCase.php(249): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(2315): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(2238): PHPUnit\Framework\TestCase->invokeHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter), 'testBeforeTestM...', 'testBeforeTestM...')
#7 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(474): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#8 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestRunner.php(98): PHPUnit\Framework\TestCase->runBare()
#9 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestCase.php(337): PHPUnit\Framework\TestRunner->run(Object(ExampleDatabaseTest))
#10 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#11 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#12 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(62): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\src\TextUI\Application.php(200): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\xampp\htdocs\codeigniter4_2024\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\xampp\htdocs\codeigniter4_2024\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
